version: '3.4'

x-env: &x-env
  DB_HOST: db
  DB_PORT: 3306
  DB_USER: osuweb
  DB_PASS: ''
  DB_DATABASE: osu
  THREADS: 8

services:
  pp:
    build:
      context: ./docker
    volumes:
      - .:/data
    working_dir: /data
    environment:
      <<: *x-env
      DOCKER: 1
    command: [ './docker/run.sh' ]
